title: Research projects of Rahul Kumar
description: A collection of research projects by Rahul Kumar, Assistant Professor in Educational Studies at Brock University.
show_downloads: true
google_analytics:
theme: jekyll-theme-leap-day
