on:
  push:
  pull_request:
    types: [opened, synchronize]
jobs:
  build:
    runs-on: ubuntu-latest
    name: script/cibuild
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.0
          bundler-cache: true
      - name: Set execute permissions for custom scripts
        run: |
          chmod +x script/cibuild
          chmod +x scripts/bootstrap
          chmod +x scripts/validate-html
      - name: build
        run: script/bootstrap
      - name: test
        run: script/cibuild
